### ISSUE TITLE
investigating modified SDK changes

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [CudoVentures/cudos-node#105]
actionable goals:

- [x] investigate modified SDK version (0.45.3) vs targeted SDK version (0.45.16) (overview)
- [x] investigate bank @dao-notional
- [x] investigate staking @tnv1
- [x] investigate group @tropicaldog

Deliverables: short summary

**Comment by catconcat** [comment]
@nghuyenthevinh2000  The x/group module is copied from Cosmos SDK v0.46.0-rc1, with some minor modifications. I think it's safe to delete/disable the module.

**Comment by tnv1** [comment]
Here is my note for compare cudos `cosmos-sdk` fork version from `v0.45.3` versus original `cosmos-sdk` `v0.45.16`. ([link](https://www.notion.so/nvlabs/Compare-cudos-cosmos-sdk-v0-45-3-fork-changes-versus-cosmos-sdk-original-v0-45-16-b910de8119934905bd108690a38b5550?pvs=4)). 
It has changes from 4 modules:

1. `x/staking`
* Change of `DefaultPowerReduction`
* Modified logic of `CreateValidator` in `x/staking/keeper/msg_server.go`
It added checking logic for validate `MinSelfDelegation`
* Modified logic of `func (msg MsgCreateValidator) ValidateBasic() error ` in `x/staking/types/msg.go`. It is same in `CreateValidator`
2. `x/crisis`
* Modified logic of `VerifyInvariant` in `x/crisis/keeper/msg_server.go`
3. `x/bank`
* Modified logic of `BurnCoins` in `x/bank/keeper/keeper.go`. It added check if `amount.Denom == burnDenom` with `var burnDenom = "acudos"` then move this token to community pool.
4. `x/group`
* Added new module `x/group`

**Comment by dao-notional** [comment]
Cause the function `BurnCoin` in `bank` module. Specifically, it is added the check: `amount.Denom == burnDenom` to remove token from module account, and add it to community pool. So we can write custom module in application, and remove this custom logic inside forked source code.
