### ISSUE TITLE
panic: minimum self delegation must be more than 2000000000000000000000000: invalid request

### ISSUE THREAD

**Issue by leezhiengammobox** [CudoVentures/cudos-node#35]
Can't seem to run with the latest code from github, no such problem from previous version:

10:56PM INF starting ABCI with Tendermint
10:56PM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
10:56PM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:56PM INF Starting localClient service connection=query impl=localClient module=abci-client
10:56PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:56PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:56PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:56PM INF Starting EventBus service impl=EventBus module=events
10:56PM INF Starting PubSub service impl=PubSub module=pubsub
10:56PM INF Starting IndexerService service impl=IndexerService module=txindex
10:56PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
10:56PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
10:56PM INF asserting crisis invariants inv=0/11 module=x/crisis name=distribution/nonnegative-outstanding
10:56PM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
10:56PM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/reference-count
10:56PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/module-account
10:56PM INF asserting crisis invariants inv=4/11 module=x/crisis name=bank/nonnegative-outstanding
10:56PM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/total-supply
10:56PM INF asserting crisis invariants inv=6/11 module=x/crisis name=gov/module-account
10:56PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
10:56PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
10:56PM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
10:56PM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
10:56PM INF asserted all invariants duration=0.888728 height=0 module=x/crisis
**panic: minimum self delegation must be more than 2000000000000000000000000: invalid request**

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x2286e08, 0xc0000520b0}, {0x22943e0, 0xc000dc4e00}, {{0x0, 0x0}, {0xc0015b3290, 0xb}, 0x0, {0x24241d13, ...}, ...}, ...}, ...)
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/x/genutil/gentx.go:113 +0x274
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x2286e08, 0xc0000520b0}, ...}, ...)
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/x/genutil/module.go:99 +0x15e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2286e08, 0xc0000520b0}, {0x22943e0, 0xc000dc4e00}, {{0x0, 0x0}, {0xc0015b3290, 0xb}, 0x0, ...}, ...}, ...)
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/types/module/module.go:307 +0x29d
github.com/CudoVentures/cudos-node/app.(*App).InitChainer(_, {{0x2286e08, 0xc0000520b0}, {0x22943e0, 0xc000dc4e00}, {{0x0, 0x0}, {0xc0015b3290, 0xb}, 0x0, ...}, ...}, ...)
        /home/nftuser/caicai-node/app/app.go:624 +0x12e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001018680, {{0x24241d13, 0xed9efe2fb, 0x0}, {0xc0015b3290, 0xb}, 0xc000ce8180, {0x31720c0, 0x0, 0x0}, ...})
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000c064e0, {{0x24241d13, 0xed9efe2fb, 0x0}, {0xc0015b3290, 0xb}, 0xc000ce8180, {0x31720c0, 0x0, 0x0}, ...})
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xa8?, {{0x24241d13, 0xed9efe2fb, 0x0}, {0xc0015b3290, 0xb}, 0xc000ce8180, {0x31720c0, 0x0, 0x0}, ...})
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1d8b08f, 0x7}}, {0xc0015b3290, 0xb}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d13e60, {0x2294d58, 0xc0000b4c30})
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1d8b08f, 0x7}}, {0xc0015b3290, 0xb}, 0x1, 0x0, ...}, ...)
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000dcac80, {0x2283cd0, 0xc0001f7ae0}, 0xc0015c5670, {0x226d440, 0xc00011bab8}, 0x0?, 0x0?, 0xc0015c57d0, {0x2287c40, ...}, ...)
        /home/nftuser/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x228b3b0, 0xc000f78cb0}, ...}, ...)
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/server/start.go:263 +0x75b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0004ccc80?, {0xc000021dc0?, 0x0?, 0x2?})
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0004ccc80, {0xc000021da0, 0x2, 0x2})
        /home/nftuser/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bdfb80)
        /home/nftuser/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nftuser/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/nftuser/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000b85b40, 0x1c})
        /home/nftuser/pkg/mod/github.com/!cudo!ventures/cosmos-sdk@v0.0.0-20220413115949-5f86bd3c94e9/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/nftuser/caicai-node/cmd/cudos-noded/main.go:16 +0x65

**Comment by avalkov** [comment]
https://github.com/CudoVentures/cudos-builders/blob/cudos-dev/tools/init-local-node-without-docker/init.sh
Use that script to run it.
